-- MySQL Script generated by MySQL Workbench
-- 04/04/17 12:03:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ZES_SVISS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ZES_SVISS` ;

-- -----------------------------------------------------
-- Schema ZES_SVISS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ZES_SVISS` DEFAULT CHARACTER SET utf8 ;
USE `ZES_SVISS` ;

-- -----------------------------------------------------
-- Table `ZES_SVISS`.`zesaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`zesaccess` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`zesaccess` (
  `AccessLevelID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AccessLevelName` VARCHAR(45) NOT NULL,
  `Permissions` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`AccessLevelID`),
  UNIQUE INDEX `AccessLevelName_UNIQUE` (`AccessLevelName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`user` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`user` (
  `UserNr` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AccessLevelID` INT(10) UNSIGNED NOT NULL,
  `PersName` VARCHAR(45) NOT NULL,
  `VacationLeft` TINYINT(3) UNSIGNED NOT NULL DEFAULT '25' COMMENT 'in days',
  `OverTimeLeft` INT(11) NOT NULL DEFAULT '0' COMMENT 'in minutes',
  `Username` VARCHAR(45) NOT NULL,
  `EMail` VARCHAR(50) NOT NULL,
  `Hiredate` DATE NOT NULL,
  `Password` VARCHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `WeekTime` DECIMAL(5,2) NULL DEFAULT NULL COMMENT 'in hours',
  `Disabled` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UserNr`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `EMail_UNIQUE` (`EMail` ASC),
  INDEX `AccessLeve_idx` (`AccessLevelID` ASC),
  CONSTRAINT `User_AccessLevel_FK`
    FOREIGN KEY (`AccessLevelID`)
    REFERENCES `ZES_SVISS`.`zesaccess` (`AccessLevelID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`absence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`absence` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`absence` (
  `AbsenceID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserNr` INT(10) UNSIGNED NOT NULL,
  `AbsenceType` VARCHAR(30) NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NOT NULL,
  `Reason` VARCHAR(45) NULL DEFAULT NULL,
  `Acknowledged` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`AbsenceID`, `UserNr`),
  INDEX `PersNr_FK_idx` (`UserNr` ASC),
  CONSTRAINT `Absence_PersNr_FK`
    FOREIGN KEY (`UserNr`)
    REFERENCES `ZES_SVISS`.`user` (`UserNr`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`approveruser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`approveruser` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`approveruser` (
  `ApproverNr` INT(10) UNSIGNED NOT NULL,
  `UserNr` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ApproverNr`, `UserNr`),
  INDEX `USER_USER_FK_idx` (`UserNr` ASC),
  CONSTRAINT `APPROVER_USER_FK`
    FOREIGN KEY (`ApproverNr`)
    REFERENCES `ZES_SVISS`.`user` (`UserNr`)
    ON DELETE CASCADE,
  CONSTRAINT `USER_USER_FK`
    FOREIGN KEY (`UserNr`)
    REFERENCES `ZES_SVISS`.`user` (`UserNr`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`holiday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`holiday` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`holiday` (
  `HolidayDate` DATE NOT NULL,
  `HolidayComment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HolidayDate`, `HolidayComment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`sollzeiten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`sollzeiten` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`sollzeiten` (
  `SollZeitenID` INT NOT NULL AUTO_INCREMENT,
  `UserNr` INT(10) UNSIGNED NOT NULL,
  `Inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SollZeitenID`),
  INDEX `PersNr_idx` (`UserNr` ASC),
  CONSTRAINT `SollZeit_PersNr_FK`
    FOREIGN KEY (`UserNr`)
    REFERENCES `ZES_SVISS`.`user` (`UserNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`userholidayovertimehistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`userholidayovertimehistory` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`userholidayovertimehistory` (
  `MonthTS` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UserNr` INT UNSIGNED NOT NULL,
  `Overtime` INT(11) NOT NULL,
  `Vacation` TINYINT(4) NOT NULL,
  PRIMARY KEY (`MonthTS`, `UserNr`),
  INDEX `User_History_FK_idx_idx` (`UserNr` ASC),
  CONSTRAINT `User_History_FK_idx`
    FOREIGN KEY (`UserNr`)
    REFERENCES `ZES_SVISS`.`user` (`UserNr`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`worktime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`worktime` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`worktime` (
  `TimeID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserNr` INT(10) UNSIGNED NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NULL DEFAULT NULL,
  `BreakTime` INT(11) NOT NULL DEFAULT '0',
  `StartComment` VARCHAR(100) NULL DEFAULT NULL,
  `EndComment` VARCHAR(100) NULL DEFAULT NULL,
  `SollStartTime` TIME NOT NULL,
  `SollEndTime` TIME NOT NULL,
  PRIMARY KEY (`TimeID`, `UserNr`),
  INDEX `WorkTime_PersNr_FK_idx` (`UserNr` ASC),
  CONSTRAINT `WorkTime_PersNr_FK`
    FOREIGN KEY (`UserNr`)
    REFERENCES `ZES_SVISS`.`user` (`UserNr`))
ENGINE = InnoDB
AUTO_INCREMENT = 420
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ZES_SVISS`.`SollZeitPerDay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZES_SVISS`.`SollZeitPerDay` ;

CREATE TABLE IF NOT EXISTS `ZES_SVISS`.`SollZeitPerDay` (
  `SollZeitenID` INT NOT NULL,
  `DayID` ENUM('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN') NOT NULL,
  `SollStartTime` TIME NOT NULL,
  `SollEndTime` TIME NOT NULL,
  PRIMARY KEY (`DayID`, `SollZeitenID`),
  INDEX `FK_SollZeitenPerDay_idx` (`SollZeitenID` ASC),
  CONSTRAINT `FK_SollZeitenPerDay`
    FOREIGN KEY (`SollZeitenID`)
    REFERENCES `ZES_SVISS`.`sollzeiten` (`SollZeitenID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

INSERT INTO `ZESAccess` (`AccessLevelID`, `AccessLevelName`, `Permissions`) VALUES
(1, 'Admin', 'ALL'),
(2, 'Approver', 'EDIT_ACCOUNT;VIEW_ALL_ABSENCES;ACKNOWLEDGE_USERS;EVALUATE_ALL;'),
(3, 'Reader', 'VIEW_ALL_TIMES;EVALUATE_ALL;EDIT_ACCOUNT;'),
(4, 'User', 'INPUT_TIME;EDIT_ACCOUNT;VIEW_ALL_ABSENCES;EVALUATE_SELF;');

INSERT INTO `User` (`UserNr`, `AccessLevelID`, `PersName`, `VacationLeft`, `OverTimeLeft`, `Username`, `EMail`, `Hiredate`, `Password`, `WeekTime`, `Disabled`) VALUES
(1, 1, 'AdminUser', 25, 0, 'admin', 'mod@sviss.at', '2016-01-01', 'c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec', '0.00', 0);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;











